### ISSUE TITLE
Not preventing duplicate emails

### ISSUE THREAD

**Issue by icambron** [omniauth/omniauth-identity#4]
I'm using Mongoid and OmniAuth Identity, only requiring email address.  The sign-up form is allowing me to create multiple identities with the same email address. I would have expected some sort of error there, saying that email address is already taken. Am I missing something?

**Comment by andyroberts** [comment]
I know this issue is *very* old, but on first glance it looks like it could still be a bug.

It looks to me that @icambron is right that omniauth-identity only applies `validates_uniqueness_of key` if the dev sets the key explicitly. I suspect the typical case involves developers sticking with the default 'email' key, thus never calling the `auth_key=` setter.

So it seems inconsistent to me. Is it preferable to just leave this to the developer to specify in model validations, or should identity enforce uniqueness of the key directly. I'm inclined towards the latter.

Either way, once again the documentation is lacking.

cc @pboling Any thoughts?

**Comment by pboling** [comment]
@andyroberts The behavior should be consistent, for sure.  Perhaps the identity enforcement should be optional in all scenarios.

There are situations where people use an identity key for logins on some accounts, but other accounts login via different means, and don't require a unique key.  So it may not be a universal requirement, and those scenarios may have complex validations built around it, which would necessitate disabling the basic enforcement here.

**Comment by andyroberts** [comment]
I find it slightly odd that Identity wouldn't enforce uniqueness itself. The `locate(key)` certainly expects key to be unique:

```ruby
        # Locate an identity given its unique login key.
        #
        # @abstract
        # @param [String] key The unique login key.
        # @return [Model] An instance of the identity model class.
        def locate(key)
          raise NotImplementedError
        end
```

The README makes no reference to handling uniqueness. I would expect therefore it's assumed that the key uniqueness is enforced by Identity.

If @icambron is in fact correct, and for years the default case in Identity is in fact not validating uniqueness itself, then either 

a) users are frequently handling it themselves, or 
b) they are completely missing this unexpected blind-spot

I actually need to establish whether `validates_uniqueness_of` is being called or not for the default key (`email`). I was only glancing at the code and didn't spot a call, but I could be wrong. That's what I'll do next when I have some more time to spend.

**Comment by pboling** [comment]
> The locate(key) certainly expects key to be unique

But only because that is a normal case.  In some systems it might be a composite uniqueness (only unique when combined with a condition on other data, i.e. contextually unique.  I guess I am suggesting that if we do not currently enforce it by default, it would be a good "opt-in", or at least an "opt-out", configuration for two reasons.

I think your 'a' is true - people generally configure uniqueness themselves (often with an "allow nulls").

**Comment by pboling** [comment]
> I actually need to establish whether validates_uniqueness_of is being called or not for the default key (email).

https://github.com/omniauth/omniauth-identity/search?q=validates_uniqueness_of

It is called, if, and only if, you use the `auth_key` macro as in the [example in the README](https://github.com/omniauth/omniauth-identity#activerecord):
```
class Identity < OmniAuth::Identity::Models::ActiveRecord
  auth_key :email    # optional: specifies the field within the model that will be used during the login process
                     # defaults to email, but may be username, uid, login, etc.

  # Anything else you want!
end
```

The `auth_key` macro *is* optional, but if you don't use it you'll need to do what it does, more or less, on your own.
