### ISSUE TITLE
Gem hosted at Rubygems is different from the one on Github

### ISSUE THREAD

**Issue by eugeneotto** [omniauth/omniauth-identity#48]
The omniauth-identity gem on Rubygems has the same version as the one on Github (1.1.0), but the code is different. A quick reference point: the docs on Github reference a locate_conditions option, whereas the docs on Rubygems do not: http://rubydoc.info/gems/omniauth-identity/1.1.0/frames

For anyone who needs the locate_conditions feature, you can get it by install the gem with this line in your Gemfile: 

gem 'omniauth-identity', git: 'https://github.com/intridea/omniauth-identity.git'

**Comment by andyroberts** [comment]
No longer relevant. 

v1.1.1 was released in July 2013 that would have satisfied this issue.

I've updated the README so that users can be quickly reminded that it's possible to source the code directly from github rather than rubygems if there's the need to use the latest code until it's officially released.
