### ISSUE TITLE
Not verifying the email address??

### ISSUE THREAD

**Issue by peterept** [omniauth/omniauth-identity#72]
Hi,

If I understand correctly, omniauth-identity is allowing the user to associate an email+password for login. But there is no check to make sure the email actually belongs to that user. They are granted the permission immeadiately.

Now, my worry is with the trend of multi omniauth strategies , say I have well known user joe@mycompany.com that logged in via Facebook, but not Identity. Then I come along and I login using his email address and make up a password, won't I get access to his account?

That is based on some of the blogs I read that associate multiple omni auth strategies to the same account via email address.

Let me know,

Peter

**Comment by laneystroup** [comment]
Hi Peter,

You have to custom code this part, since omniauth-identity is purely a registration/login system. For example I use the following method in my Identity model triggered on create:

  def send_confirmation
    self.update(:confirmation_token => SecureRandom.hex(32))
    AuthenticationMailer.confirmation_email(self).deliver
  end

The following method to check whether the account is confirmed or not:

  def confirmed?
    !confirmation_token.present?
  end

And the following to locate the account to be confirmed, and clear the confirmation token:

  def self.authenticate_confirmation_token(token)
    identity = self.find_by(confirmation_token: token)
    unless token.nil? or identity.nil? or identity.confirmation_expired?
      identity.update(:confirmation_token => nil)
      return identity
    else
      return false
    end
  end

Hopefully that gives you a start. FYI, you can follow the same strategy for password reset, reconfirmation (i.e. changing email addresses), account lockouts, and remember_me tokens (you can use an authenticatable_salt based on the password to eliminate the need for an extra column, and to allow multiple devices to be remembered).

**Comment by pboling** [comment]
The answer given is correct.  This gem gives you 80% of the functionality you need, but does require some custom coding if you want to have more complex (or more secure) strategies.
